package pers.jun.pojo;

public class ItemScroll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_scroll.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_scroll.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_scroll.home_scroll
     *
     * @mbg.generated
     */
    private String homeScroll;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_scroll.id
     *
     * @return the value of item_scroll.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_scroll.id
     *
     * @param id the value for item_scroll.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_scroll.item_id
     *
     * @return the value of item_scroll.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_scroll.item_id
     *
     * @param itemId the value for item_scroll.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_scroll.home_scroll
     *
     * @return the value of item_scroll.home_scroll
     *
     * @mbg.generated
     */
    public String getHomeScroll() {
        return homeScroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_scroll.home_scroll
     *
     * @param homeScroll the value for item_scroll.home_scroll
     *
     * @mbg.generated
     */
    public void setHomeScroll(String homeScroll) {
        this.homeScroll = homeScroll == null ? null : homeScroll.trim();
    }
}